

<section> 
	<form action="" method="Post" >
	  <label>funcionario</label>   
	  <input  name = "funcionario" type = "TEXT" value="<?php echo $funcionario['funcionario'] ?? ''; ?>"  />
      <label>funcao</label>	
	  <input  name   = "funcao"  type = "TEXT" value="<?php echo $funcionario['funcao'] ?? ''; ?>" />
	  <label>ativo</label>
	  <input  name   = "ativo"  type = "TEXT" value="<?php echo $funcionario['ativo'] ?? ''; ?>" />
	  <label>idusuario</label>
	  <input  name   = "id_usuario"  type = "TEXT" value="<?php echo $funcionario['id_usuario'] ?? ''; ?>" />
	  <input type = "submit"  value = "salvar" name = "submit" />
	 </form>  
 </section>
 